use_frameworks!

platform :ios, '9.0'

target 'WDAudioMuteSwitch_Example' do
  pod 'WDAudioMuteSwitch', :path => '../'

  target 'WDAudioMuteSwitch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
